### ISSUE TITLE
Let .viewport() also get values by name

### ISSUE THREAD

**Issue by ryanve** [ryanve/verge#14]
#### [Current implementation](../blob/1.9.1/src/verge.js#L45-L52)

``` js
verge.viewport() // => object with .width and .height properties
```
#### Proposed extension

``` js
verge.viewport('width') // => .width value
verge.viewport('height') // => .height value
```

**Comment by Merri** [comment]
I'd instead consider renaming `viewportW` and `viewportH` to `viewportWidth` and `viewportHeight` as passing magical strings is a poor API design imo.
