### ISSUE TITLE
Watch functionality

### ISSUE THREAD

**Issue by boye** [ryanve/verge#16]
Hi @ryanve,

At @esites we use verge.js in our projects quite often. That said, I caught myself writing small wrappers around `verge.inViewport` to handle scroll and resize events. So, I decided to wrap this functionality up in a 'plugin' of sorts.

It exposes the `verge.watch` method that accepts an object with the following properties:

* `target`: the DOM element that needs to be watched
* `callback`: callback that will be invoked when the target is in the viewport. When passing an array with two functions, the first will be executed when the target is in the viewport, the second when it's out.
* `interval`; optional interval that determines how many times `verge.inViewport` will be called

Example calls:
```js
verge.watch({
    target: document.getElementById('target'),
    callback: function (e) {
        // do something
        // `this` points to the target DOM element
        // the first passed argument is a reference to the corresponding event object (either scroll or resize)
    }
});

verge.watch({
    target: document.getElementById('target'),
    callback: [showElement, hideElement]
});
```
Some characteristics:

* vanilla JS and no dependencies
* lightweight; only 2kb (minified) when merged with verge.js
* performant; embraces [John Resig's best practice](http://ejohn.org/blog/learning-from-twitter/) on working with scroll/resize events. So no complex calculations while scrolling/resizing, `verge.inViewport` is being called within a `setInterval`. Hence the possibility to pass along a an interval to overrule the default interval (150ms).
* tests available and jshint compliant
* tested in Firefox, Safari, Chrome, Opera and IE8+

For now the code is located in the [forked repo](https://github.com/boye/verge/tree/master/src). If you would like to see this functionality merged (say, as part of 2.0) I could create a PR :)

Cheers!

**Comment by JPustkuchen** [comment]
Hi @ryanve and @boye ,

thank you very much for your discussion and this great library. It would be nice to have best-practise examples like the one above plus @ryanve 's comment in the README to prevent typical mistakes. The named events like scroll and resize are surely used very often with this library.

What do you think?
