### ISSUE TITLE
Put it on bower

### ISSUE THREAD

**Issue by Narretz** [ryanve/verge#17]
Would it be possible to put verge on bower? Since it's dependent on the DOM, it makes sense to have it on bower, too.

**Comment by entr** [comment]
No, it's not. At least now it can't be found on bower registry. It needs to be explicitly registered using `bower register` having a `bower.json` in place. http://bower.io/docs/creating-packages/

**Comment by ryanve** [comment]
huh, it was there at one point...does `bower install ryanve/verge` work?

**Comment by entr** [comment]
For some reason it worked :) probably because it's on npm, but how reliable is that? Also there's no `main` specified.

**Comment by Narretz** [comment]
Bower is a dead end, so let's close it.
