### ISSUE TITLE
verge online library not on https

### ISSUE THREAD

**Issue by virenv** [ryanve/verge#46]
Our website is an https, we cannot include your library because it is served from an http server. Would you mind if we can host your library on https ? Our website is ToolsQA.com

Resource I am talking about is: http:////airve.github.io//js//verge//verge.min.js

**Comment by ryanve** [comment]
Sure host wherever you want!

FYI [unpkg](https://unpkg.com) has every version https://unpkg.com/verge@latest/ will redirect to latest version

https://airve.github.io isn't meant for permanent use because they're not versioned
